services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    project.command_handler_registry:
        class: App\Common\App\Command\Handler\Registry\CommandHandlerRegistry
        calls:
            - [registerHandler, [!php/const App\Module\Project\App\Command\CreateProjectCommand::TYPE, '@App\Module\Project\App\Command\Handler\CreateProjectCommandHandler']]
            - [registerHandler, [!php/const App\Module\Project\App\Command\EditProjectCommand::TYPE, '@App\Module\Project\App\Command\Handler\EditProjectCommandHandler']]
            - [registerHandler, [!php/const App\Module\Project\App\Command\DeleteProjectCommand::TYPE, '@App\Module\Project\App\Command\Handler\DeleteProjectCommandHandler']]
            - [registerHandler, [!php/const App\Module\Project\App\Command\AddTeamMemberCommand::TYPE, '@App\Module\Project\App\Command\Handler\AddTeamMemberCommandHandler']]
            - [registerHandler, [!php/const App\Module\Project\App\Command\RemoveTeamMemberCommand::TYPE, '@App\Module\Project\App\Command\Handler\RemoveTeamMemberCommandHandler']]

    project.command_bus:
        class: App\Common\App\Command\Bus\AppCommandBus
        arguments:
            $commandHandlerRegistry: '@project.command_handler_registry'

    issue.command_handler_registry:
        class: App\Common\App\Command\Handler\Registry\CommandHandlerRegistry
        calls:
            - [registerHandler, [!php/const App\Module\Issue\App\Command\CreateIssueCommand::TYPE, '@App\Module\Issue\App\Command\Handler\CreateIssueCommandHandler']]
            - [registerHandler, [!php/const App\Module\Issue\App\Command\EditIssueCommand::TYPE, '@App\Module\Issue\App\Command\Handler\EditIssueCommandHandler']]
            - [registerHandler, [!php/const App\Module\Issue\App\Command\DeleteIssueCommand::TYPE, '@App\Module\Issue\App\Command\Handler\DeleteIssueCommandHandler']]
            - [registerHandler, [!php/const App\Module\Issue\App\Command\AddIssueFieldCommand::TYPE, '@App\Module\Issue\App\Command\Handler\AddIssueFieldCommandHandler']]
            - [registerHandler, [!php/const App\Module\Issue\App\Command\EditIssueFieldCommand::TYPE, '@App\Module\Issue\App\Command\Handler\EditIssueFieldCommandHandler']]
            - [registerHandler, [!php/const App\Module\Issue\App\Command\DeleteIssueFieldCommand::TYPE, '@App\Module\Issue\App\Command\Handler\DeleteIssueFieldCommandHandler']]
            - [registerHandler, [!php/const App\Module\Issue\App\Command\AddCommentCommand::TYPE, '@App\Module\Issue\App\Command\Handler\AddCommentCommandHandler']]
            - [registerHandler, [!php/const App\Module\Issue\App\Command\EditCommentCommand::TYPE, '@App\Module\Issue\App\Command\Handler\EditCommentCommandHandler']]
            - [registerHandler, [!php/const App\Module\Issue\App\Command\DeleteCommentCommand::TYPE, '@App\Module\Issue\App\Command\Handler\DeleteCommentCommandHandler']]

    issue.command_bus:
        class: App\Common\App\Command\Bus\AppCommandBus
        arguments:
            $commandHandlerRegistry: '@issue.command_handler_registry'

    user.command_handler_registry:
        class: App\Common\App\Command\Handler\Registry\CommandHandlerRegistry
        calls:
            - [ registerHandler, [ !php/const App\Module\User\App\Command\AddUserCommand::TYPE, '@App\Module\User\App\Command\Handler\AddUserCommandHandler' ] ]
            - [ registerHandler, [ !php/const App\Module\User\App\Command\EditUserCommand::TYPE, '@App\Module\User\App\Command\Handler\EditUserCommandHandler' ] ]
            - [ registerHandler, [ !php/const App\Module\User\App\Command\DeleteUserCommand::TYPE, '@App\Module\User\App\Command\Handler\DeleteUserCommandHandler' ] ]

    user.command_bus:
        class: App\Common\App\Command\Bus\AppCommandBus
        arguments:
            $commandHandlerRegistry: '@user.command_handler_registry'