services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    app.event.handler.issue.domain.issue_field_added:
        class: 'App\Module\Issue\App\Event\Domain\Handler\IssueFieldAddedEventHandler'
        arguments:
            $type: !php/const App\Module\Issue\Domain\Event\IssueFieldAdded::TYPE

    app.event.handler.issue.domain.issue_field_edited:
        class: 'App\Module\Issue\App\Event\Domain\Handler\IssueFieldEditedEventHandler'
        arguments:
            $type: !php/const App\Module\Issue\Domain\Event\IssueFieldEdited::TYPE

    app.event.handler.issue.domain.issue_field_deleted:
        class: 'App\Module\Issue\App\Event\Domain\Handler\IssueFieldDeletedEventHandler'
        arguments:
            $type: !php/const App\Module\Issue\Domain\Event\IssueFieldDeleted::TYPE

    app.event.domain_event_dispatcher:
        class: App\Common\App\Event\DomainEventDispatcher
        calls:
            - [subscribe, ['@app.event.handler.issue.domain.issue_field_added']]
            - [subscribe, ['@app.event.handler.issue.domain.issue_field_edited']]
            - [subscribe, ['@app.event.handler.issue.domain.issue_field_deleted']]