services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    event.issue.domain.issue_field_added:
        class: 'App\Module\Issue\App\Event\Domain\Handler\IssueFieldAddedEventHandler'
        arguments:
            $type: !php/const App\Module\Issue\Domain\Event\IssueFieldAdded::TYPE

    App\Common\App\Event\DomainEventDispatcher:
        calls:
            - [subscribe, ['@event.issue.domain.issue_field_added']]