services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    authentication.user.provider:
        class: App\Framework\Infrastructure\Security\Provider\UserProvider

    authentication.authenticator:
        class: App\Framework\Infrastructure\Security\Authenticator\Authenticator