doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        driver: 'pdo_pgsql'
        charset: utf8
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\Module\User:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/user'
                prefix: 'App\Module\User'
                alias: User
