security:
    enable_authenticator_manager: true
    providers:
        user_provider:
            id: 'authentication.user.provider'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: user_provider

            entry_point: authentication.authenticator
            custom_authenticators:
                - authentication.authenticator

            pattern: ^/api/
            logout:
                path: /api/logout

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    access_control:
         - { path: ^/api/auth$, roles: PUBLIC_ACCESS }
         - { path: ^/api, roles: ROLE_USER }
#         - { path: ^/profile/get, roles: PUBLIC_ACCESS }
