api_auth:
  path: /api/auth

api_get_project:
  path: /api/project/{id}
  controller: App\Controller\Api\Project\ProjectManagementController::getProject
  requirements:
    id: '\d+'

api_projects_list:
  path: /api/projects
  controller: App\Controller\Api\Project\ProjectSettingsController::projectsList
  methods: GET

api_create_project:
  path: /api/project/create
  controller: App\Controller\Api\Project\ProjectManagementController::createProject
  methods: POST

api_delete_project:
  path: /api/project/delete
  controller: App\Controller\Api\Project\ProjectManagementController::deleteProject
  methods: POST

api_edit_project:
  path: /api/project/edit
  controller: App\Controller\Api\Project\ProjectManagementController::editProject

api_get_issue:
  path: /api/issue/{issueCode}
  controller: App\Controller\Api\Issue\IssueManagementController::getIssue
  methods: GET

api_create_issue:
  path: /api/issue/create
  controller: App\Controller\Api\Issue\IssueManagementController::createIssue

api_edit_route:
  path: /api/issue
  controller: App\Controller\Api\Issue\IssueManagementController::editIssue
  methods: POST

api_issues_list:
  path: /api/issue/search
  controller: App\Controller\Api\Issue\IssueManagementController::issuesList
  methods: POST

api_add_issue_field:
  path: /api/issue-field/add
  controller: App\Controller\Api\Issue\IssueFieldController::addField
  methods: POST

api_edit_issue_field:
  path: /api/issue-field/edit
  controller: App\Controller\Api\Issue\IssueFieldController::editField
  methods: POST

api_delete_issue_field:
  path: /api/issue-field/delete
  controller: App\Controller\Api\Issue\IssueFieldController::deleteField
  methods: POST

api_issue_field_list:
  path: /api/issue-field/list/{projectId}
  controller: App\Controller\Api\Issue\IssueFieldController::listForProject
  methods: GET
  requirements:
    projectId: '\d+'

api_user_list:
  path: /api/users
  controller: App\Controller\Api\User\UserController::list
  methods: GET

api_add_user:
  path: /api/user/add
  controller: App\Controller\Api\User\UserController::addUser
  methods: POST

api_edit_user:
  path: /api/user/edit
  controller: App\Controller\Api\User\UserController::editUser
  methods: POST

api_delete_user:
  path: /api/user/delete
  controller: App\Controller\Api\User\UserController::deleteUser
  methods: POST

api_add_team_member:
  path: /api/team-member/add
  controller: App\Controller\Api\Project\TeamController::addMember
  methods: POST

api_remove_team_member:
  path: /api/team-member/remove
  controller: App\Controller\Api\Project\TeamController::removeMember
  methods: POST