api_auth:
  path: /api/auth

api_get_project:
  path: /api/project/{id}
  controller: App\Controller\Api\Project\ProjectManagementController::getProject
  requirements:
    id: '\d+'

api_create_project:
  path: /api/project/create
  controller: App\Controller\Api\Project\ProjectManagementController::createProject