api_auth:
  path: /api/auth

api_get_project:
  path: /api/project/{id}
  controller: App\Controller\Api\Project\ProjectManagementController::getProject
  requirements:
    id: '\d+'

api_projects_list:
  path: /api/projects
  controller: App\Controller\Api\Project\ProjectSettingsController::projectsList
  methods: GET

api_create_project:
  path: /api/project/create
  controller: App\Controller\Api\Project\ProjectManagementController::createProject

api_get_issue:
  path: /api/issue/{issueCode}
  controller: App\Controller\Api\Issue\IssueManagementController::getIssue
  methods: GET

api_create_issue:
  path: /api/issue/create
  controller: App\Controller\Api\Issue\IssueManagementController::createIssue

api_edit_route:
  path: /api/issue
  controller: App\Controller\Api\Issue\IssueManagementController::editIssue
  methods: POST

api_issues_list:
  path: /api/issue/search
  controller: App\Controller\Api\Issue\IssueManagementController::issuesList
  methods: POST

api_add_issue_field:
  path: /api/issue-field/add
  controller: App\Controller\Api\Issue\IssueFieldController::addField
  methods: POST