version: "3.3"

services:
  php-fpm:
    image: vadimmakerov/tracker-app-dev
    build: './'
    container_name: tracker_app
    restart: always
    env_file:
      - ../.env
      - ../.env.local
    stdin_open: true
    tty: true
    depends_on:
      - db
      - fuzzy
    volumes:
      - ./../:/var/www
      - ./php/php.ini:/usr/local/etc/php/php.ini-development

  nginx:
    image: nginx:latest
    container_name: tracker_nginx
    restart: always
    volumes:
      - ./../public:/var/www
      - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"

  db:
    image: postgres
    container_name: tracker_db
    volumes:
      - './postgres/data:/var/lib/postgresql/data'
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234

  fuzzy:
    image: vadimmakerov/tracker-fuzzy-dev
    build: ../fuzzy/
    container_name: tracker_fuzzy
    volumes:
      - '../fuzzy/:/usr/src/app'
    ports:
      - 9000:9000
    environment:
      PORT: 9000
      DEBUG: 1

#  redis:
#    image: redis
#    container_name: tracker_redis
#    restart: always
#    volumes:
#      - ./redis/conf/redis.conf:/usr/local/etc/redis
#      - ./redis/data:/data/storage
#    command: redis-server