api:
    path: /api/{wildcard}
    controller: App\Controller\ApiController
    requirements:
        wildcard: .*

frontend:
    path: /{wildcard}
    controller: App\Controller\FrontendController
    requirements:
        wildcard: .*
